models/Currency.php
<?php
/**
 * Created by PhpStorm.
 * User: N_Juraev
 * Date: 01.09.2019
 * Time: 8:47
 */

namespace app\models;

use yii\db\ActiveRecord;

class Currency extends ActiveRecord
{

    public function rules()
    {

        return [
            [['currency','rate_to_main'],'required'],
            ['currency','string'],
            ['currency','unique','targetAttribute'=>'currency']
        ];
    }
}

controllers/CurrencyController.php
<?php
/**
 * Created by PhpStorm.
 * User: N_Juraev
 * Date: 01.09.2019
 * Time: 8:42
 */

namespace app\controllers;

use Yii;
use app\models\Currency;

class CurrencyController extends SiteController
{
    public function actionIndex()
    {
        $currency = new Currency();
        $data = Currency::find()->all();

        return $this->render('index', ['currency' => $currency, 'currency_data' => $data]);
    }

    public function actionSave()
    {
        $currency = new Currency();

        if ($currency->load(Yii::$app->request->post()) && $currency->validate()) {
            $currency->currency = strtoupper($currency->currency);
            // если в базе уже указана основная валюта необходимо его изменить на обычную
            $currency->save();

            return $this->redirectBack('success', 'Данные сохранены');
        } else {

            return $this->redirectBack('error', 'Не удалось сохранить данные');
        }

    }
}

views/currency/_form.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
Use yii\helpers\Url;
$form=ActiveForm::begin(['action'=>Url::to(['currency/save','layout'=>'horizontal'])]);?>
<?= $form->field($currency,'currency')->textInput(['placeholder'=>'USD'])->label('Валюта') ?>
<?= $form->field($currency,'rate_to_main')->textInput()->label('Курс по отношению к основной') ?>
<?= Html::submitButton('Добавить',['class'=>'btn btn-success']) ?>
<?php ActiveForm::end();?>

views/currency/index.php
<div class="row">
    <div class="col-md-10">
        <?= $this->render('_form',['currency'=>$currency]) ?>
    </div>
</div>
<br>
<table class="table table-responsive">
    <thead>
    <tr>
        <th>#</th>
        <th>Валюта</th>
        <th>Курс по отношению к основной</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($currency_data as $datum):?>
        <tr>
            <td><?= $datum->id ?></td>
            <td><?= $datum->currency ?></td>
            <td><?= $datum->rate_to_main ?></td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>