models/Exchange.php
<?php
/**
 * Created by PhpStorm.
 * User: N_Juraev
 * Date: 01.09.2019
 * Time: 8:45
 */

namespace app\models;

use yii\db\ActiveRecord;

class Exchange extends ActiveRecord
{
    public $balance;

    public function rules()
    {
        return [
          [['name','api_key'],'required'],
          ['name','unique','targetAttribute'=>'name']
        ];
    }

    public function getExchangeBalances()
    {
        return $this->hasMany(ExchangeBalance::className(),['exchange_id'=>'id']);
    }

    public function getCurrencies(){
        return $this->hasMany(Currency::className(), ['id' => 'currency_id'])
            ->via('exchangeBalances');
    }
}

controllers/CurrencyController.php
<?php
/**
 * Created by PhpStorm.
 * User: N_Juraev
 * Date: 01.09.2019
 * Time: 8:42
 */

namespace app\controllers;

use Yii;
use app\models\Currency;

class CurrencyController extends SiteController
{
    public function actionIndex()
    {
        $currency = new Currency();
        $data = Currency::find()->all();

        return $this->render('index', ['currency' => $currency, 'currency_data' => $data]);
    }

    public function actionSave()
    {
        $currency = new Currency();

        if ($currency->load(Yii::$app->request->post()) && $currency->validate()) {
            $currency->currency = strtoupper($currency->currency);
            // если в базе уже указана основная валюта необходимо его изменить на обычную
            $currency->save();

            return $this->redirectBack('success', 'Данные сохранены');
        } else {

            return $this->redirectBack('error', 'Не удалось сохранить данные');
        }

    }
}

controllers/ExchangeController.php
<?php
/**
 * Created by PhpStorm.
 * User: N_Juraev
 * Date: 01.09.2019
 * Time: 8:42
 */

namespace app\controllers;

use Yii;
use app\models\Currency;
use app\models\Exchange;
use app\models\ExchangeBalance;

class ExchangeController extends SiteController
{
    /**
     * Exchange index page action.
     *
     * @return view
     */
    public function actionIndex()
    {
        $exchange = new Exchange();
        $exchange_data = Exchange::find()->all();
        $currency = Currency::find()->all();

        return $this->render('index', ['exchange' => $exchange, 'exchange_data' => $exchange_data, 'currency' => $currency]);
    }

    /**
     * Save new exchange. Save exchange balance in loop
     *
     * @return redirect back
     */
    function actionSave()
    {
        $exchange = new Exchange();

        if ($exchange->load(Yii::$app->request->post()) && $exchange->validate()) {
            $exchange->save();

            foreach (Yii::$app->request->post('balance') as $key => $item) {
                $exchangeBalance = new ExchangeBalance();
                $exchangeBalance->exchange_id = $exchange->id;
                $exchangeBalance->currency_id = $key;
                $exchangeBalance->balance = $item;
                $exchangeBalance->save();
            }
            return $this->redirectBack('success', 'Данные сохранены');
        } else
            return $this->redirectBack('error', 'Не удалось сохранить данные');
    }

    public function actionDelete()
    {
        $id = Yii::$app->request->get('id');
        if (!$id)
            $this->redirectBack('error', 'Неизвестный ID');

        $exchange = Exchange::findOne(['id' => $id]);
        ExchangeBalance::deleteAll(['exchange_id' => $exchange->id]);
        $exchange->delete();

        return $this->redirectBack('success', 'Запись удалена');

    }
}

views/exchange/_form.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

$form=\yii\bootstrap\ActiveForm::begin(['action'=>Url::to(['exchange/save'])])
?>
<?= $form->field($exchange,'name')->textInput() ?>
<?= $form->field($exchange,'api_key')->textInput() ?>
<div class="row">
    <div class="col-md-12">
        <h4 >Баланс</h4>
    </div>
    <?php if(!count($currency)):?>
    <div class="alert alert-warning">
        <a href="<?= Url::to(['currency/index']) ?>">Добавить валюту</a>
    </div>

    <?php else:?>
        <?php foreach ($currency as $c):?>
            <div class="col-md-4" style="margin-top: 10px;">
               <label><?= $c->currency ?></label> <?= Html::input('text','balance['.$c->id.']',0,['class'=>'form-control'])?>
            </div>
        <?php endforeach;?>
    <?php endif;?>
</div>
<br>

<?= Html::submitButton('Добавить биржу',['class'=>'btn btn-success']) ?>
<?php \yii\bootstrap\ActiveForm::end();?>

views/exchange/balances.php
<?php
$i=1;
?>
<table class="table table-sm table-responsive">
    <thead>
    <tr>
        <th>#</th>
        <th>Название</th>
        <th>Баланс</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($exchanges as $exchange):?>
        <tr>
            <td><?= $i++; ?></td>
            <td><?= $exchange['name']; ?></td>

            <td><?php
                foreach ($exchange['balances'] as $key=>$balance){
                    echo $key. " ".$balance. "; ";
                }
                ?></td>

        </tr>
    <?php endforeach;?>
    </tbody>

</table>

views/exchange/index.php
<?php
use yii\helpers\Url;
$i=1;
?>

<div class="row">
    <div class="col-md-10">
        <?= $this->render('_form',['exchange'=>$exchange,'currency'=>$currency]) ?>
    </div>

</div>
<hr>
<br>
<div class="row">
    <table class="table table-sm table-responsive">
        <thead>
        <tr>
            <th>#</th>
            <th>Название</th>
            <th>API ключ</th>
            <th>Баланс</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($exchange_data as $ed):?>
            <tr>
                <td><?= $i++; ?></td>
                <td><?= $ed->name; ?></td>
                <td><?= $ed->api_key; ?></td>
                <td><?php
                    foreach ($ed->exchangeBalances as $exchangeBalance){
                        echo $exchangeBalance->balance. " ".$ed->getCurrencies()->where(['id'=>$exchangeBalance->currency_id])->one()->currency. "; ";
                    }
                    ?></td>
                <td>
                    <a href="<?= Url::to(['exchange/delete','id'=>$ed->id]) ?>">Удалить</a>
                </td>
            </tr>
        <?php endforeach;?>
        </tbody>

    </table>

</div>